/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IBSCollateralPairInterface extends ethers.utils.Interface {
  functions: {
    "collateralOfAccount(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "collateralOfAccount",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "collateralOfAccount",
    data: BytesLike
  ): Result;

  events: {
    "Liquidate(address,address,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Liquidate"): EventFragment;
}

export class IBSCollateralPair extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBSCollateralPairInterface;

  functions: {
    collateralOfAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "collateralOfAccount(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  collateralOfAccount(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "collateralOfAccount(address)"(
    _account: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    collateralOfAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collateralOfAccount(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Liquidate(
      pair: string | null,
      asset: string | null,
      user: string | null,
      liquidatedCollateralAmount: null,
      liquidator: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        pair: string;
        asset: string;
        user: string;
        liquidatedCollateralAmount: BigNumber;
        liquidator: string;
      }
    >;
  };

  estimateGas: {
    collateralOfAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "collateralOfAccount(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    collateralOfAccount(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "collateralOfAccount(address)"(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
