/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface VaultInterface extends ethers.utils.Interface {
  functions: {
    "FLASHLOAN_CALLBACK_SUCCESS()": FunctionFragment;
    "balanceOf(address,address)": FunctionFragment;
    "blackSmithTeam()": FunctionFragment;
    "c_0x630f40d2(bytes32)": FunctionFragment;
    "c_0xd117f7be(bytes32)": FunctionFragment;
    "c_0xeca1878e(bytes32)": FunctionFragment;
    "c_0xff8e4d68(bytes32)": FunctionFragment;
    "deposit(address,address,address,uint256)": FunctionFragment;
    "flashFee(address,uint256)": FunctionFragment;
    "flashLoan(address,address,uint256,bytes)": FunctionFragment;
    "flashLoanRate()": FunctionFragment;
    "getCodeAddress()": FunctionFragment;
    "initialize(uint256,address)": FunctionFragment;
    "maxFlashLoan(address)": FunctionFragment;
    "paused()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "send(address,address,uint256)": FunctionFragment;
    "toShare(address,uint256)": FunctionFragment;
    "toUnderlying(address,uint256)": FunctionFragment;
    "totals(address)": FunctionFragment;
    "transfer(address,address,uint256)": FunctionFragment;
    "transferToNewTeam(address)": FunctionFragment;
    "updateCode(address)": FunctionFragment;
    "updateFlashloanRate(uint256)": FunctionFragment;
    "withdraw(address,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "FLASHLOAN_CALLBACK_SUCCESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blackSmithTeam",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "c_0x630f40d2",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_0xd117f7be",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_0xeca1878e",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "c_0xff8e4d68",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flashFee",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoanRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCodeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "maxFlashLoan",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toShare",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toUnderlying",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToNewTeam",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "updateCode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateFlashloanRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "FLASHLOAN_CALLBACK_SUCCESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blackSmithTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_0x630f40d2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_0xd117f7be",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_0xeca1878e",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "c_0xff8e4d68",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flashFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flashLoanRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCodeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxFlashLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toShare", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferToNewTeam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFlashloanRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "CodeUpdated(bytes32,address)": EventFragment;
    "Deposit(address,address,address,uint256,uint256)": EventFragment;
    "FlashLoan(address,address,uint256,uint256,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Transfer(address,address,address,uint256)": EventFragment;
    "TransferControl(address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "UpdateFlashLoanRate(uint256)": EventFragment;
    "Withdraw(address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CodeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FlashLoan"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferControl"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateFlashLoanRate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class Vault extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VaultInterface;

  functions: {
    FLASHLOAN_CALLBACK_SUCCESS(overrides?: CallOverrides): Promise<[string]>;

    "FLASHLOAN_CALLBACK_SUCCESS()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    balanceOf(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "balanceOf(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    blackSmithTeam(overrides?: CallOverrides): Promise<[string]>;

    "blackSmithTeam()"(overrides?: CallOverrides): Promise<[string]>;

    c_0x630f40d2(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0x630f40d2(bytes32)"(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    c_0xd117f7be(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xd117f7be(bytes32)"(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    c_0xeca1878e(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xeca1878e(bytes32)"(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    c_0xff8e4d68(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0xff8e4d68(bytes32)"(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    deposit(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "deposit(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    flashFee(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "flashFee(address,uint256)"(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "flashLoan(address,address,uint256,bytes)"(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    flashLoanRate(overrides?: CallOverrides): Promise<[BigNumber]>;

    "flashLoanRate()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCodeAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { codeAddress: string }>;

    "getCodeAddress()"(
      overrides?: CallOverrides
    ): Promise<[string] & { codeAddress: string }>;

    initialize(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(uint256,address)"(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    maxFlashLoan(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "maxFlashLoan(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<[string]>;

    send(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "send(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toShare(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { share: BigNumber }>;

    "toShare(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { share: BigNumber }>;

    toUnderlying(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    "toUnderlying(address,uint256)"(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>;

    totals(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "totals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    transfer(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transfer(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferToNewTeam(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferToNewTeam(address)"(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updateCode(address)"(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateFlashloanRate(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updateFlashloanRate(uint256)"(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdraw(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  FLASHLOAN_CALLBACK_SUCCESS(overrides?: CallOverrides): Promise<string>;

  "FLASHLOAN_CALLBACK_SUCCESS()"(overrides?: CallOverrides): Promise<string>;

  balanceOf(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "balanceOf(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  blackSmithTeam(overrides?: CallOverrides): Promise<string>;

  "blackSmithTeam()"(overrides?: CallOverrides): Promise<string>;

  c_0x630f40d2(
    c__0x630f40d2: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x630f40d2(bytes32)"(
    c__0x630f40d2: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  c_0xd117f7be(
    c__0xd117f7be: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xd117f7be(bytes32)"(
    c__0xd117f7be: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  c_0xeca1878e(
    c__0xeca1878e: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xeca1878e(bytes32)"(
    c__0xeca1878e: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  c_0xff8e4d68(
    c__0xff8e4d68: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0xff8e4d68(bytes32)"(
    c__0xff8e4d68: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  deposit(
    _token: string,
    _from: string,
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "deposit(address,address,address,uint256)"(
    _token: string,
    _from: string,
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  flashFee(
    arg0: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "flashFee(address,uint256)"(
    arg0: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  flashLoan(
    _receiver: string,
    _token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "flashLoan(address,address,uint256,bytes)"(
    _receiver: string,
    _token: string,
    _amount: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  flashLoanRate(overrides?: CallOverrides): Promise<BigNumber>;

  "flashLoanRate()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCodeAddress(overrides?: CallOverrides): Promise<string>;

  "getCodeAddress()"(overrides?: CallOverrides): Promise<string>;

  initialize(
    _flashLoanRate: BigNumberish,
    _blackSmithTeam: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(uint256,address)"(
    _flashLoanRate: BigNumberish,
    _blackSmithTeam: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  maxFlashLoan(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  "maxFlashLoan(address)"(
    _token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  "proxiableUUID()"(overrides?: CallOverrides): Promise<string>;

  send(
    _token: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "send(address,address,uint256)"(
    _token: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toShare(
    _token: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "toShare(address,uint256)"(
    _token: string,
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  toUnderlying(
    _token: string,
    _share: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "toUnderlying(address,uint256)"(
    _token: string,
    _share: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totals(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "totals(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  transfer(
    _token: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transfer(address,address,uint256)"(
    _token: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferToNewTeam(
    _newTeam: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferToNewTeam(address)"(
    _newTeam: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCode(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updateCode(address)"(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateFlashloanRate(
    _newRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updateFlashloanRate(uint256)"(
    _newRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    _token: string,
    _from: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdraw(address,address,address,uint256)"(
    _token: string,
    _from: string,
    _to: string,
    _shares: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    FLASHLOAN_CALLBACK_SUCCESS(overrides?: CallOverrides): Promise<string>;

    "FLASHLOAN_CALLBACK_SUCCESS()"(overrides?: CallOverrides): Promise<string>;

    balanceOf(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    blackSmithTeam(overrides?: CallOverrides): Promise<string>;

    "blackSmithTeam()"(overrides?: CallOverrides): Promise<string>;

    c_0x630f40d2(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x630f40d2(bytes32)"(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    c_0xd117f7be(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xd117f7be(bytes32)"(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    c_0xeca1878e(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xeca1878e(bytes32)"(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    c_0xff8e4d68(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0xff8e4d68(bytes32)"(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "deposit(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    flashFee(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "flashFee(address,uint256)"(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "flashLoan(address,address,uint256,bytes)"(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    flashLoanRate(overrides?: CallOverrides): Promise<BigNumber>;

    "flashLoanRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCodeAddress(overrides?: CallOverrides): Promise<string>;

    "getCodeAddress()"(overrides?: CallOverrides): Promise<string>;

    initialize(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(uint256,address)"(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: CallOverrides
    ): Promise<void>;

    maxFlashLoan(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFlashLoan(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<string>;

    send(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "send(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toShare(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toShare(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toUnderlying(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toUnderlying(address,uint256)"(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totals(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "totals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transfer(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferToNewTeam(
      _newTeam: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferToNewTeam(address)"(
      _newTeam: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCode(newAddress: string, overrides?: CallOverrides): Promise<void>;

    "updateCode(address)"(
      newAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateFlashloanRate(
      _newRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateFlashloanRate(uint256)"(
      _newRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "withdraw(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { owner: string; spender: string; value: BigNumber }
    >;

    CodeUpdated(
      uuid: null,
      codeAddress: null
    ): TypedEventFilter<
      [string, string],
      { uuid: string; codeAddress: string }
    >;

    Deposit(
      token: string | null,
      from: string | null,
      to: string | null,
      amount: null,
      shares: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        token: string;
        from: string;
        to: string;
        amount: BigNumber;
        shares: BigNumber;
      }
    >;

    FlashLoan(
      borrower: string | null,
      token: string | null,
      amount: null,
      feeAmount: null,
      receiver: string | null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, string],
      {
        borrower: string;
        token: string;
        amount: BigNumber;
        feeAmount: BigNumber;
        receiver: string;
      }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    Transfer(
      token: string | null,
      from: string | null,
      to: string | null,
      amount: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { token: string; from: string; to: string; amount: BigNumber }
    >;

    TransferControl(
      _newTeam: null
    ): TypedEventFilter<[string], { _newTeam: string }>;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;

    UpdateFlashLoanRate(
      newRate: null
    ): TypedEventFilter<[BigNumber], { newRate: BigNumber }>;

    Withdraw(
      token: string | null,
      from: string | null,
      to: string | null,
      shares: null,
      amount: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        token: string;
        from: string;
        to: string;
        shares: BigNumber;
        amount: BigNumber;
      }
    >;
  };

  estimateGas: {
    FLASHLOAN_CALLBACK_SUCCESS(overrides?: CallOverrides): Promise<BigNumber>;

    "FLASHLOAN_CALLBACK_SUCCESS()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOf(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    blackSmithTeam(overrides?: CallOverrides): Promise<BigNumber>;

    "blackSmithTeam()"(overrides?: CallOverrides): Promise<BigNumber>;

    c_0x630f40d2(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x630f40d2(bytes32)"(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_0xd117f7be(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xd117f7be(bytes32)"(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_0xeca1878e(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xeca1878e(bytes32)"(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    c_0xff8e4d68(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0xff8e4d68(bytes32)"(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "deposit(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    flashFee(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "flashFee(address,uint256)"(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "flashLoan(address,address,uint256,bytes)"(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    flashLoanRate(overrides?: CallOverrides): Promise<BigNumber>;

    "flashLoanRate()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCodeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    "getCodeAddress()"(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(uint256,address)"(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    maxFlashLoan(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "maxFlashLoan(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<BigNumber>;

    send(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "send(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toShare(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toShare(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    toUnderlying(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "toUnderlying(address,uint256)"(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totals(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "totals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transfer(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferToNewTeam(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferToNewTeam(address)"(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updateCode(address)"(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateFlashloanRate(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updateFlashloanRate(uint256)"(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdraw(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    FLASHLOAN_CALLBACK_SUCCESS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "FLASHLOAN_CALLBACK_SUCCESS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    blackSmithTeam(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "blackSmithTeam()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_0x630f40d2(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x630f40d2(bytes32)"(
      c__0x630f40d2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_0xd117f7be(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xd117f7be(bytes32)"(
      c__0xd117f7be: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_0xeca1878e(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xeca1878e(bytes32)"(
      c__0xeca1878e: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    c_0xff8e4d68(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0xff8e4d68(bytes32)"(
      c__0xff8e4d68: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "deposit(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    flashFee(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "flashFee(address,uint256)"(
      arg0: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    flashLoan(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "flashLoan(address,address,uint256,bytes)"(
      _receiver: string,
      _token: string,
      _amount: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    flashLoanRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "flashLoanRate()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCodeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCodeAddress()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(uint256,address)"(
      _flashLoanRate: BigNumberish,
      _blackSmithTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    maxFlashLoan(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "maxFlashLoan(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proxiableUUID()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    send(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "send(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toShare(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toShare(address,uint256)"(
      _token: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toUnderlying(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toUnderlying(address,uint256)"(
      _token: string,
      _share: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totals(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "totals(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transfer(address,address,uint256)"(
      _token: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferToNewTeam(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferToNewTeam(address)"(
      _newTeam: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updateCode(address)"(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateFlashloanRate(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updateFlashloanRate(uint256)"(
      _newRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdraw(address,address,address,uint256)"(
      _token: string,
      _from: string,
      _to: string,
      _shares: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
